### ISSUE TITLE
Feature request for PbsnodesParser

### ISSUE THREAD

**Issue by moravveji** [gjbex/vsc-tools-lib#20]
Dear Geert Jan

May I ask you to let the PbsnodesParser also parse the two following fields from the pbsnodes output?
- `gpus`
- `gpu_status`
For the former, I want to capture the number of physical devices per gpu node, and for the latter, i would like to distinguish which device is actively involved in a job. In this regard, the following fields can be also interesting (maybe we decide to use them in the near future), e.g.
`gpu_memory_total=16280 MB;gpu_memory_used=788 MB;gpu_mode=Exclusive_Process;gpu_state=Unallocated;gpu_utilization=38%;gpu_memory_utilization=6%;gpu_temperature=45 C`

Thanks in advance
Ehsan

**Comment by gjbex** [comment]
@moravveji All features you request have already been implemented and are available in the development branch.

**Comment by moravveji** [comment]
hmmm ... then, I'm not sure whether that is pushed to the development branch, because I cannot see the `gpus` and `gpu_status` attributes for one randomly selected gpu node. 

I already made sure my devel branch is updated:
```bash
# git branch
* development
  feature/ehsan
  master
# git pull origin development
From https://github.com/gjbex/vsc-tools-lib
 * branch            development -> FETCH_HEAD
Already up to date.
```

Next, I pick out one random GPU node from the long list of nodes parsed by PbsnodesParser, and I see this:
`r23g35
        state = free
        np = 36
        properties = r23g,singleisland,type_skylake_gpu,skylake,beeond
        ntype = cluster
        status = opsys=linux,uname=Linux r23g35 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64,sessions=107568,nsessions=1,nusers=1,idletime=171671,totmem=193543120kb,availmem=185111080kb,physmem=192494544kb,ncpus=36,loadave=0.76,gres=,netload=2802793315164,state=free,varattr=puppethpc=20200319-152;puppethpccode=20200423-4564-gitfb8f2740;sudo=1-8-23-4-el7_7-2;kernel=3-10-0-957-27-2-el7-x86_64=None,cpuclock=OnDemand:1000MHz,macaddr=74:46:a0:72:c5:04,version=6.1.3,rectime=1587720831`

Am I missing something?

**Comment by gjbex** [comment]
@moravveji Yes, you are missing something.  Have a look at tests/test/pbsnodes_test.py which illustrates the new features.

**Comment by moravveji** [comment]
I see now. The NodeStatus.__str__ method does not spit out all available info within the class. 
Closing this issue now.
Thx.
